コメントいただいた点と数か所細部を修正
shimane-u-pim/proj-2024-magazine pull request #1
Opened 2024-12-02 01:16 UTC by Takuto1529

コメントありがとうございました。
コメントいただいた点とその他数か所を修正してみました。

2024-12-02 02:07 UTC, mkaraki requested changes
@Takuto1529  コメントした点について軽く修正してもらえればいいと思います。
修正は同じブランチで行ってください。自動でこちらのPRに適応されます。
再レビュー後、一応 @palalaw のレビューを入れて、その後こちらでマージします。

2024-12-02 02:07 UTC, mkaraki commented on articles/80-sysadmin.tex
> +どうぞよろしく。
この行いらないかも

2024-12-02 02:07 UTC, mkaraki commented on articles/80-sysadmin.tex
> +  \item ウェブサイト (\url{https://www.pim.gr.jp} など)
`()`の付け方が、前にスペースを空ける方法と開けない方法が混在しているので、統一しましょう。
個人的には開けた方が見た目が良くなる印象です。

2024-12-02 02:07 UTC, mkaraki commented on articles/80-sysadmin.tex
> +Uptime KumaとGrafana Cloudというサーバ死活監視システムを用いて、サーバが予期せず落ちていないか等監視しており、障害が発生したらシステム管理者が対応に当たっています。
先頭に`また、`を付けるといいかも

2024-12-02 05:00 UTC, mkaraki requested changes
@Takuto1529 言葉が足らず申し訳ないです。自己紹介の修正だけやったらもう一度私にレビューをかけてください。

2024-12-02 05:00 UTC, mkaraki commented on articles/80-sysadmin.tex
> -\section{自己紹介}
ごめんなさい。
どうぞよろしくが不要かなという意味でした。
自己紹介は最終行を除いて、元の状態のを使いましょう。

2024-12-03 07:45 UTC, Takuto1529 commented on articles/80-sysadmin.tex
> -\section{自己紹介}
そういうことでしたか。了解です。自己紹介の最終行のみ削除した形で再度プルリク投げますね。

2024-12-03 09:35 UTC, mkaraki approved these changes

2024-12-03 09:36 UTC, mkaraki commented
@palalaw レビューをお願いします。
マージはまだしないでください。こちらでHTMLに書き換えてからマージします。

2024-12-04 19:19 UTC, palalaw reviewed
読みやすくていい感じだと思われます

2024-12-10 11:01 UTC, merged