81-designPCbag
shimane-u-pim/proj-2024-magazine pull request #2
Opened 2024-12-03 00:23 UTC by minerva-jupiter

2024-12-03 04:43 UTC, mkaraki commented
@minerva-jupiter ファイル名は`80-`から始めてください。
また、次回から自分をアサインして、事前に割り当てられたレビュワーに対してレビューを依頼してください。

2024-12-03 04:44 UTC, mkaraki commented
@minerva-jupiter @JetJaguar-PSX 
まだマージしないでください。最終的にこのPR上でHTMLに差し替えて、こちらでマージします。

2024-12-03 04:47 UTC, mkaraki requested changes
ファイル名は80-から始めてください。

2024-12-03 04:51 UTC, minerva-jupiter commented
[invalid noun]
@mikadoSMNをreviewerに設定できません。

2024-12-03 04:56 UTC, minerva-jupiter commented
> [invalid noun] @mikadoSMNをreviewerに設定できません。

resolved

2024-12-03 05:27 UTC, mkaraki requested changes

2024-12-03 05:27 UTC, mkaraki commented on articles/80-designPCbag.md
> +当たり前のこと過ぎて上の表には書いていませんが、この鞄の一番の目的はノートPCを持ち運ぶことです。それに従って鞄の仕様決定にはノートPCがどのようなものであるかを把握して置かなければなりません。なので、14型までのノートPCのサイズと重量を調べてまとめ、表にしてみて最大値を取っていくことによって大体のノートPCに対応できるようにしました。一般的なノートPCの中で15.6型という比較的大きいノート
- `NECのLAVIE N14がもっともサイズ`文内に`の`が大量に出ています。

2024-12-03 05:27 UTC, mkaraki commented on articles/80-designPCbag.md
> +他の要件を満たす方法も考えていきます。まず、防水は防水の布を使います。ここで重要なのは撥水では不十分であるということです。PCが水没するとかなりの損害になります。そのため、しっかりと防水であるものを選びます。私は帆布カバン信者なので、ラミネートされている帆布を使うことにしました。ちなみにお金に余裕があるなら、パラフィン加工(簡単に言うと蠟を染み込ませた)の帆布などは質感も良くなります。最後に硬め
- `まず、防水は防水の布を使います。`: 少し言い回しが冗長かも…？
- `蠟`: 機種依存文字です。修正してください。
- `なぜならばスポンジゴムを固定しておくために裏地の実装が必須になってくるので`: `ため$`のほうがいいかも
- `費用が裏地の分とスポンジゴムで`: 片方にしか`の分`が付いていないので、いっそのことなくしてもいいかも
- `一つ幾ら`: `一つに幾ら`のほうがいいかも

2024-12-03 05:27 UTC, mkaraki commented on articles/80-designPCbag.md
> +カバンをどのような形・サイズにするかが決まったので、型紙を引く段階に移ります。型紙を引くと言いつつも直方体の形で、私がよく使っているテンプレート(fig1)があるので、そちらに今回のサイズを適応する形にしたいと思います。しかし、今回のカバンの厚みは20mmと非常に小さいので、fig1にある{厚み/2}というものが非常に小さくなります。そこで、今回は片側からカバンの横の部分の布を提供する形に変更す
- `(fig1)` -> `(fig. 1)`
- `そちらに今回のサイズを適応する形にしたいと思います`: `適用`のほうがあってる説 ([Ref](https://support.microsoft.com/ja-jp/office/%E6%97%A2%E5%AD%98%E3%81%AE%E3%83%97%E3%83%AC%E3%82%BC%E3%83%B3%E3%83%86%E3%83%BC%E3%82%B7%E3%83%A7%E3%83%B3%E3%81%AB%E3%83%86%E3%83%B3%E3%83%97%E3%83%AC%E3%83%BC%E3%83%88%E3%82%92%E9%81%A9%E7%94%A8%E3%81%99%E3%82%8B-43f7fc75-db26-433b-8248-9fcd0093006b#:~:text=%E3%83%86%E3%83%B3%E3%83%97%E3%83%AC%E3%83%BC%E3%83%88%E3%82%92%E6%96%B0%E3%81%97%E3%81%84%E3%83%97%E3%83%AC%E3%82%BC%E3%83%B3%E3%83%86%E3%83%BC%E3%82%B7%E3%83%A7%E3%83%B3%E3%81%BE%E3%81%9F%E3%81%AF%E6%97%A2%E5%AD%98%E3%81%AE%E3%83%97%E3%83%AC%E3%82%BC%E3%83%B3%E3%83%86%E3%83%BC%E3%82%B7%E3%83%A7%E3%83%B3%E3%81%AB%E9%81%A9%E7%94%A8%E3%81%99%E3%82%8B%E5%A0%B4%E5%90%88%E3%81%AF))
- `今回は片側からカバンの横の部分の布を提供する形に変更することにします。`: `の`が多いです

2024-12-03 05:27 UTC, mkaraki commented on articles/80-designPCbag.md
> +続いて肩紐の実装について決めていきます。今回、肩紐はカバンから4つのDかん等を出して、肩紐についたナスカンでそのうち2つを選択するという方式をとることにします。私が以前に作成したメッセンジャーバックは側面の布に肩紐が縫い付けられていたのですが、これだと用意に肩紐を交換することができないほか、側面が引っ張られるので底面にかかっている重量は底面と側面の布の縫い目を経由して肩紐にかかることになります。
- `メッセンジャーバック` -> `メッセンジャーバッグ`のほうが適切かと
- `中央部にシワが寄りやすくなってしまうことがあったため`: ひらがな部分が少し長いです
- `それらを解消するために底面から布が上向きに地の目で続いている場所にDかん等を設置することで耐久性や形状の保持が期待できると考え`: 句読点を入れましょう。

2024-12-03 05:27 UTC, mkaraki commented on articles/80-designPCbag.md
> +これによって布に線を引いたらそれに沿って布を切断し、端の処理を適切にし、縫い合わせていきます。このあたりは家庭科の知識なので、できなかったりわからなかったら、義務教育に立ち返ってみることをおすすめします。冗談はさておき、カバンを一つ作るだけなら、これに好みの肩紐をつけるだけで完成でございます。
- `できなかったり`: `たり`が単独で使われています
- `義務教育に立ち返ってみることをおすすめします。`: 煽らないでください。これは外部向けの出版物です。

2024-12-03 06:01 UTC, minerva-jupiter commented on articles/80-designPCbag.md
> +当たり前のこと過ぎて上の表には書いていませんが、この鞄の一番の目的はノートPCを持ち運ぶことです。それに従って鞄の仕様決定にはノートPCがどのようなものであるかを把握して置かなければなりません。なので、14型までのノートPCのサイズと重量を調べてまとめ、表にしてみて最大値を取っていくことによって大体のノートPCに対応できるようにしました。一般的なノートPCの中で15.6型という比較的大きいノート
削減できる「の」を削減しました。

2024-12-03 06:05 UTC, minerva-jupiter commented on articles/80-designPCbag.md
> +他の要件を満たす方法も考えていきます。まず、防水は防水の布を使います。ここで重要なのは撥水では不十分であるということです。PCが水没するとかなりの損害になります。そのため、しっかりと防水であるものを選びます。私は帆布カバン信者なので、ラミネートされている帆布を使うことにしました。ちなみにお金に余裕があるなら、パラフィン加工(簡単に言うと蠟を染み込ませた)の帆布などは質感も良くなります。最後に硬め
- 分割しました。「まず、防水の機能です。この実現は防水の布を使います。」
- 蝋->ロウ
- 分割しました。「なぜならばスポンジゴムを固定しておくために裏地の実装が必須になってくるので、費用が裏地の分とスポンジゴムとで多くかかってしまうからです。」
- なくすか迷いましたがニュアンスを維持するためにこちらに適応しました。「スポンジゴムとで」
- 明確に意図を示すため「鞄一つに対して幾ら」に修正しました

2024-12-03 06:06 UTC, minerva-jupiter commented on articles/80-designPCbag.md
> +カバンをどのような形・サイズにするかが決まったので、型紙を引く段階に移ります。型紙を引くと言いつつも直方体の形で、私がよく使っているテンプレート(fig1)があるので、そちらに今回のサイズを適応する形にしたいと思います。しかし、今回のカバンの厚みは20mmと非常に小さいので、fig1にある{厚み/2}というものが非常に小さくなります。そこで、今回は片側からカバンの横の部分の布を提供する形に変更す
- 修正しました
- テンプレートに含まれている文字に実際に必要な数字を入れて型紙を生成しているので、適用ではなく、適応を使用しています。
- 修正案が思いつきませんでした。「今回は片側からカバンの横の部分の布を提供する形に変更することにします。」

2024-12-03 06:08 UTC, minerva-jupiter commented on articles/80-designPCbag.md
> +続いて肩紐の実装について決めていきます。今回、肩紐はカバンから4つのDかん等を出して、肩紐についたナスカンでそのうち2つを選択するという方式をとることにします。私が以前に作成したメッセンジャーバックは側面の布に肩紐が縫い付けられていたのですが、これだと用意に肩紐を交換することができないほか、側面が引っ張られるので底面にかかっている重量は底面と側面の布の縫い目を経由して肩紐にかかることになります。
- `メッセンジャーバッグ`に訂正
- 修正案が思いつきませんでした。
- 句点を追加しました。`それらを解消するために、底面から布が上向きに地の目で続いている場所にDかん等を設置することで、耐久性や形状の保持が期待できると考え、このような方式にしました。`

2024-12-03 06:10 UTC, minerva-jupiter commented on articles/80-designPCbag.md
> +これによって布に線を引いたらそれに沿って布を切断し、端の処理を適切にし、縫い合わせていきます。このあたりは家庭科の知識なので、できなかったりわからなかったら、義務教育に立ち返ってみることをおすすめします。冗談はさておき、カバンを一つ作るだけなら、これに好みの肩紐をつけるだけで完成でございます。
- 「たり」を使わない表現に変更しました。
- 煽りと思われないように次の文に補足をしていましたが、表現を大幅に変更しました。

2024-12-03 09:42 UTC, mkaraki requested changes

2024-12-03 09:42 UTC, mkaraki commented on articles/80-designPCbag.md
> +カバンをどのような形・サイズにするかが決まったので、型紙を引く段階に移ります。型紙を引くと言いつつも直方体の形で、私がよく使っているテンプレート(fig.1)があるので、そちらに今回のサイズを適応する形にしたいと思います。しかし、今回のカバンの厚みは20mmと非常に小さいので、fig1にある{厚み/2}というものが非常に小さくなります。そこで、今回は片側からカバンの横の部分の布を提供する形に変更
- `カバンの厚みは20mmと非常に小さいので、fig1にある`: `fig1`が残っちゃってます。

2024-12-03 09:42 UTC, mkaraki commented on articles/80-designPCbag.md
> +当たり前のこと過ぎて上の表には書いていませんが、この鞄の一番の目的はノートPCを持ち運ぶことです。それに従って鞄の仕様決定にはノートPCがどのようなものであるかを把握して置かなければなりません。なので、14型までのノートPCのサイズと重量を調べてまとめ、表にしてみて最大値を取っていくことによって大体のノートPCに対応できるようにしました。一般的なノートPCの中で15.6型という比較的大きいノート
- `surface` -> `Surface`
- `vaio` -> `Vaio`
- `ThinkPad`はLenovoの製品です。`IdeaPad`と区別したいならもう1つを`IdeaPad`に変更してください。
- `LAVIE`は`NEC LAVIE`のほうがこの流れだといいかも。そうなると`Surface`も`Microsoft`付けたいところだけど…

2024-12-03 10:22 UTC, minerva-jupiter commented on articles/80-designPCbag.md
> +当たり前のこと過ぎて上の表には書いていませんが、この鞄の一番の目的はノートPCを持ち運ぶことです。それに従って鞄の仕様決定にはノートPCがどのようなものであるかを把握して置かなければなりません。なので、14型までのノートPCのサイズと重量を調べてまとめ、表にしてみて最大値を取っていくことによって大体のノートPCに対応できるようにしました。一般的なノートPCの中で15.6型という比較的大きいノート
メーカー名表記を抜いて、ブランド名で統一しました。誤表記は直しました。

2024-12-03 10:29 UTC, minerva-jupiter commented
文中に示されたfigを追加し、markdownと2つのfigのsvgを一つのフォルダ内に格納

2024-12-03 11:30 UTC, mkaraki approved these changes

2024-12-05 12:41 UTC, minerva-jupiter commented
html verを追加しました。

2024-12-09 08:29 UTC, Sunny-JP requested changes

2024-12-09 08:29 UTC, Sunny-JP commented on articles/80-designPCbag/80-designPCbag.md
> +さて、カバンに使う布をどのような形に取るかは決定したところですが、これで型紙は完成ではありません。縫い代というものをつけることで、ようやく縫えるようになります。今回は裏地を張ることも考慮に入れたいため、縫い代は20mmに設定しておきました。一般的には10mmですが、今回20mmとしたのは、裏地をつけない可能性があるため、生地の端処理を三つ折りにて行おうとするためです。端処理の方法は他にもあり、例
> 一般的には10mmですが、今回20mmとしたのは、裏地をつけない可能性があるため、生地の端処理を三つ折りにて行おうとするためです。

`因果関係の難読性`

- 提案
`一般的な縫い代は10mmですが、今回は裏地をつけない可能性があり、生地の端処理を三つ折りにて行いたいため20mmを採用しました。`

2024-12-09 08:29 UTC, Sunny-JP commented on articles/80-designPCbag/80-designPCbag.md
> +カバンをどのような形・サイズにするかが決まったので、型紙を引く段階に移ります。型紙を引くと言いつつも直方体の形で、私がよく使っているテンプレート(fig.1)があるので、そちらに今回のサイズを適応する形にしたいと思います。しかし、今回のカバンの厚みは20mmと非常に小さいので、fig.1にある{厚み/2}というものが非常に小さくなります。そこで、今回は片側からカバンの横の部分の布を提供する形に変
> ちなみに直方体ならば天面のない一般的な直方体の展開図のように、側面の布を底面の布の横を利用することを思いつくかもしれませんが、それではいくらか都合の悪いことが発生します。

`文構造の難読性`

- 提案
`ちなみに直方体ならば、天面のない一般的な直方体の展開図のように、側面に使用する布として底面部分に使用する布の余りが利用できると思われるかもしれませんが、それではいくらか都合の悪いことが発生します。`

2024-12-09 08:36 UTC, Sunny-JP commented on articles/80-designPCbag/80-designPCbag.md
> +カバンをどのような形・サイズにするかが決まったので、型紙を引く段階に移ります。型紙を引くと言いつつも直方体の形で、私がよく使っているテンプレート(fig.1)があるので、そちらに今回のサイズを適応する形にしたいと思います。しかし、今回のカバンの厚みは20mmと非常に小さいので、fig.1にある{厚み/2}というものが非常に小さくなります。そこで、今回は片側からカバンの横の部分の布を提供する形に変
`底面部分`の`部分`は不要ですね、失礼しました

2024-12-10 03:30 UTC, minerva-jupiter commented on articles/80-designPCbag/80-designPCbag.md
> +さて、カバンに使う布をどのような形に取るかは決定したところですが、これで型紙は完成ではありません。縫い代というものをつけることで、ようやく縫えるようになります。今回は裏地を張ることも考慮に入れたいため、縫い代は20mmに設定しておきました。一般的には10mmですが、今回20mmとしたのは、裏地をつけない可能性があるため、生地の端処理を三つ折りにて行おうとするためです。端処理の方法は他にもあり、例
adopt it

2024-12-10 03:30 UTC, minerva-jupiter commented on articles/80-designPCbag/80-designPCbag.md
> +カバンをどのような形・サイズにするかが決まったので、型紙を引く段階に移ります。型紙を引くと言いつつも直方体の形で、私がよく使っているテンプレート(fig.1)があるので、そちらに今回のサイズを適応する形にしたいと思います。しかし、今回のカバンの厚みは20mmと非常に小さいので、fig.1にある{厚み/2}というものが非常に小さくなります。そこで、今回は片側からカバンの横の部分の布を提供する形に変
i adopted it

2024-12-10 04:02 UTC, Sunny-JP approved these changes

2024-12-10 11:01 UTC, merged